
project_id = "ddljuawonxdnesrnclsx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.billing-automation]
verify_jwt = false

[functions.radius-client-status]
verify_jwt = false

[functions.radius-status-webhook]
verify_jwt = false

[functions.radius-sync-callback]
verify_jwt = false

[functions.generate-radius-credentials]
verify_jwt = false

[functions.get-client-wallet-transactions]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-auto-notifications]
verify_jwt = false

[functions.process-radius-records]
verify_jwt = false

[functions.test-family-bank-connection]
verify_jwt = false

[functions.family-bank-stk-push]
verify_jwt = false

[functions.family-bank-stk-callback]
verify_jwt = false

[functions.family-bank-query-status]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-c2b-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.network-automation]
verify_jwt = false

[functions.send-test-message]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
tenants = [
  {name = "realtime", db_name = "postgres", db_host = "localhost", db_port = 54322, db_user = "supabase_realtime_admin", db_password = "supabase", max_connections = 100, max_channels_per_client = 100, max_joins_per_second = 500, max_events_per_second = 500, postgres_changes_listen_interval_ms = 100}
]

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
port = 54328
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
ip_version = "ipv4"
